;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-buffer
	c-electric-delete-forward
	c-electric-semi&comma
	downcase-region
	easy-kill
	electric-newline-and-maybe-indent
	emmet-expand-line
	indent-for-tab-command
	js2-line-break
	kill-region
	mc/mark-all-dwim-or-mark-sexp
	mouse-set-region
	my/mc/insert-numbers
	org-cycle
	org-delete-char
	org-self-insert-command
	repeat-yank
	sgml-slash
	upcase-region
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	ensime-mouse-motion
	goto-line
	helm-M-x
	ignore
	js2-mode-show-node
	phi-search-migemo
	point-undo
	toggle-input-method
	))
